package com.epam.streaming

import org.apache.spark.sql.types.{DataTypes, StructType}

object Structures {
  val structHotel: StructType = new StructType()
    .add("id", DataTypes.LongType)
    .add("name", DataTypes.StringType)
    .add("country", DataTypes.StringType)
    .add("city", DataTypes.StringType)
    .add("address", DataTypes.StringType)
    .add("geoHash", DataTypes.StringType)

  val structWeather: StructType = new StructType()
    .add("lng", DataTypes.DoubleType)
    .add("lat", DataTypes.DoubleType)
    .add("weather_date", DataTypes.StringType)
    .add("geoHash", DataTypes.StringType)
    .add("temperature", DataTypes.StringType)

  val structWeatherAgg: StructType = new StructType()
    .add("weatherDate", DataTypes.StringType)
    .add("geoHash", DataTypes.StringType)
    .add("averageTemperature", DataTypes.DoubleType)

  val structWeatherHotelJoin: StructType = new StructType()
    .add("weatherDate", DataTypes.StringType)
    .add("averageTemperature", DataTypes.DoubleType)
    .add("idPk", DataTypes.LongType)
    .add("name", DataTypes.StringType)
    .add("country", DataTypes.StringType)
    .add("city", DataTypes.StringType)
    .add("address", DataTypes.StringType)

  val expediaStruct: StructType = new StructType()
    .add("hotel_id", DataTypes.LongType)
    .add("user_id", DataTypes.IntegerType)
    .add("srch_ci", DataTypes.StringType)
    .add("srch_co", DataTypes.StringType)
    .add("srch_children_cnt", DataTypes.IntegerType)

  val expediaHotelWeatherJoinStruct: StructType = new StructType()
    .add("hotel_id", DataTypes.LongType)
    .add("user_id", DataTypes.IntegerType)
    .add("srch_ci", DataTypes.StringType)
    .add("srch_co", DataTypes.StringType)
    .add("srch_children_cnt", DataTypes.IntegerType)
    .add("weatherDate", DataTypes.StringType)
    .add("averageTemperature", DataTypes.DoubleType)
    .add("idPk", DataTypes.LongType)
    .add("name", DataTypes.StringType)
    .add("country", DataTypes.StringType)
    .add("city", DataTypes.StringType)
    .add("address", DataTypes.StringType)

  val initialDateStruct = new StructType()
    .add("group_hotel_id", DataTypes.LongType)
    .add("erroneous_data_cnt", DataTypes.LongType)
    .add("short_stay_cnt", DataTypes.LongType)
    .add("standart_stay_cnt", DataTypes.LongType)
    .add("standart_extended_stay_cnt", DataTypes.LongType)
    .add("long_stay_cnt", DataTypes.LongType)
    .add("most_popular_stay_cnt", DataTypes.LongType)
    .add("most_popular_stay_type", DataTypes.StringType)

  val initialJoinExpediaDateStruct = new StructType()
    .add("group_hotel_id", DataTypes.LongType)
    .add("erroneous_data_cnt", DataTypes.LongType)
    .add("short_stay_cnt", DataTypes.LongType)
    .add("standart_stay_cnt", DataTypes.LongType)
    .add("standart_extended_stay_cnt", DataTypes.LongType)
    .add("long_stay_cnt", DataTypes.LongType)
    .add("most_popular_stay_cnt", DataTypes.LongType)
    .add("most_popular_stay_type", DataTypes.StringType)
    .add("hotel_id", DataTypes.LongType)
    .add("user_id", DataTypes.IntegerType)
    .add("srch_ci", DataTypes.StringType)
    .add("srch_co", DataTypes.StringType)
    .add("srch_children_cnt", DataTypes.IntegerType)
}
